id: A212BBB7E
base_file: fB534.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:05:12.992416
  last_modified_at: 2022-05-31 05:05:12.992423
