id: A212BBB7E
base_file: fCBB6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:05:12.994240
  last_modified_at: 2022-05-31 05:05:12.994245
